#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed_files=$(git diff --cached --name-only)

if echo "$changed_files" | grep -F -e "config.yaml" -e "config.schema.json" -e "scripts/validate-config.js" -e ".github/workflows/validate-config.yml" -e "examples/" >/dev/null; then
  echo "Running config validation..."
  npm run validate-config
fi
